
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jspdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: jhr31127**
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
